site_name: My Docs
theme:
  name: material #主题
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: 关闭自动模式
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: black # 主色
      accent: indigo # 强调色
      toggle:
        icon: material/toggle-switch
        name: 切换至夜间模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换至日间模式
  icon:
    logo: logo
  features: 
    - announce.dismiss # 可关闭公告栏
    - navigation.instant # 页面无刷新切换
    - navigation.prune
    # - header.autohide  # 自动隐藏头部
    - navigation.instant.progress # 页面切换进度条
    # - navigation.prune # 只渲染可见导航项
    - navigation.tracking # 滚动时URL锚点自动更新
    - navigation.tabs # 一级导航显示为顶部Tab
    # - navigation.tabs.sticky  # Tab栏吸顶
    - navigation.sections # 侧边栏分组
    - navigation.top # 返回顶部按钮
    - navigation.footer # 页脚显示在侧边栏
    - search.suggest # 搜索建议
    - search.highlight # 搜索高亮
    - search.share # 搜索结果分享
    - navigation.expand # 默认展开所有目录
    - navigation.indexes # 支持节索引页
    - content.tabs.link # 支持标签页链接
    - content.tooltips # 支持鼠标悬浮提示
    - content.code.copy # 代码块一键复制
    - content.code.select # 代码块一键全选
    # - content.action.edit # 编辑按钮
    # - content.action.view # 查看源码按钮
    - content.code.annotate # 代码注释

edit_uri: edit/main/docs # 编辑按钮跳转的链接 
repo_url: https://github.com/Wcowin/mkdocs-reading-time # 右上角点击跳转的链接
repo_name: MkDocs Reading Time # 右上角的名字

copyright: Copyright &copy; 2025 Wcowin # 左下角的版权声明

nav:
  - 示例页面: index.md
  # - English: mkdocs-reading-time.md
  - 更新日志:
    - blog/index.md
    
plugins:
  - search:
      # enabled: !ENV [CI, false]   #建议加上这句，不然会影响速度，本地搜索可以不需要，不影响部署时候有
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - blog:
      blog_dir: blog  # 确保博客目录配置正确
      post_date_format: full #时间
      draft: true
      draft_if_future_date: true #自动将具有未来日期的帖子标记为草稿
      post_readtime: true
      post_readtime_words_per_minute: 265  #计算帖子的阅读时间时读者每分钟预计阅读的字数
      post_url_format: "{date}/{slug}"
      pagination_per_page: 5
      pagination_url_format: "page/{page}"
      authors_file: "{blog}/.authors.yml"  #作者信息
  # - tags


markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  # - callouts
  - md_in_html
  - markdown.extensions.abbr # 支持Markdown文件上方自定义标题标签等
  - pymdownx.magiclink
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format 
  - pymdownx.arithmatex:  
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
      # baselevel: 2
      # toc_depth: 3  # 控制标题层级深度
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

hooks:
  - docs/overrides/hooks/reading_time.py